/* ==================================================================================
   ASTROPEDIA — base de datos
   Toda la información del juego vive en este objeto. Para añadir contenido nuevo
   basta con agregar una entrada más a la lista correspondiente: el resto de la
   aplicación (buscador, tarjetas, árboles de fabricación, favoritos, planetas...)
   la detecta automáticamente.
   ================================================================================== */

const PLANETS = [
  {id:'sylva',   name:'Sylva',   icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/planets/Icon_Sylva.webp', color:'#6bdc9c', order:1,
    desc:'El planeta natal e inicio de toda partida. Bosques, colinas y cuevas moderadas. El mejor lugar para aprender las bases del juego.',
    difficulty:1, level:'Inicial', primary:'Laterite', secondary:'Sphalerite',
    exclusive:'Laterite y Sphalerite en abundancia; también hay Malachite y Ammonium.',
    gases:['Hydrogen','Nitrogen'], risks:'Fauna hostil escasa; algunas plantas explosivas y espinas.',
    tips:'Construye tu base cerca de una cueva con Compound y Resin visibles: te ahorrará muchos viajes al principio.'},
  {id:'desolo',  name:'Desolo',  icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/planets/Icon_Desolo.webp', color:'#9aa5bd', order:2,
    desc:'Luna árida de Sylva, pequeña y sin atmósfera. Ideal para una primera excursión corta en cohete.',
    difficulty:1, level:'Temprano', primary:'Laterite', secondary:'Wolframite',
    exclusive:'Wolframite (Tungsteno) en cuevas; Sphalerite en montañas.',
    gases:[], risks:'Sin gases que recolectar (no tiene atmósfera). Terreno con cráteres pronunciados.',
    tips:'Aunque no tiene gases, es la fuente más cómoda de Wolframite para tu primer Chemistry Lab.'},
  {id:'calidor',name:'Calidor', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/planets/Icon_Calidor.webp', color:'#ffb066', order:3,
    desc:'Un desierto cálido y ventoso, segundo planeta desde la estrella. Buen sitio para paneles solares.',
    difficulty:2, level:'Temprano-medio', primary:'Malachite', secondary:'Titanite',
    exclusive:'Grandes yacimientos de Malachite (Copper) y Titanite (Titanium).',
    gases:['Sulfur','Methane'], risks:'Tormentas de arena que reducen visibilidad; fauna territorial.',
    tips:'Trae suficiente energía solar: la alta insolación hace que los paneles rindan al máximo aquí.'},
  {id:'vesania', name:'Vesania', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/planets/Icon_Vesania.webp', color:'#b78bff', order:4,
    desc:'Un mundo exótico cubierto de vegetación densa y colinas onduladas. Alberga enormes vetas de Litio.',
    difficulty:3, level:'Medio', primary:'Lithium', secondary:'Quartz',
    exclusive:'Litio en grandes cantidades; Hematite en cuevas profundas.',
    gases:['Hydrogen','Nitrogen','Methane'], risks:'Vegetación agresiva y terreno muy irregular; fácil perderse en cuevas profundas.',
    tips:'Es la mejor fuente de Litio del juego: llévate varios contenedores llenos antes de irte.'},
  {id:'novus',   name:'Novus',   icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/planets/Icon_Novus.webp', color:'#4fd6ff', order:5,
    desc:'Luna de Vesania con un ciclo día/noche muy corto (unos 210 segundos). Rica en Hematite y Laterite.',
    difficulty:2, level:'Medio', primary:'Hematite', secondary:'Laterite',
    exclusive:'Clústeres densos de Hematite y Laterite; Litio y Ammonium en menor medida.',
    gases:['Hydrogen','Methane'], risks:'El día/noche rápido complica la energía solar; conviene usar viento o baterías grandes.',
    tips:'Buena parada rápida para reponer combustible (Hydrazine) y batería antes de ir a Glacio o Atrox.'},
  {id:'glacio',  name:'Glacio',  icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/planets/Icon_Glacio.webp', color:'#dfefff', order:6,
    desc:'El planeta más alejado de la estrella: paisajes helados y el mejor lugar para Titanium e Iron.',
    difficulty:4, level:'Avanzado', primary:'Hematite', secondary:'Titanite',
    exclusive:'Iron y Titanium en abundancia; también Litio, Ammonium, Clay y Quartz.',
    gases:['Argon'], risks:'Frío extremo, ciclos día/noche largos (~20 min) con poca luz solar efectiva; usa energía eólica o RTG.',
    tips:'Es la mejor fuente de Argon del juego, esencial para el Steel y el Titanium Alloy.'},
  {id:'atrox',   name:'Atrox',   icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/planets/Icon_Atrox.webp', color:'#ff6b6b', order:7,
    desc:'El planeta más cercano a la estrella: niebla tóxica, plantas muy agresivas y el único lugar con Helio.',
    difficulty:5, level:'Avanzado / endgame', primary:'—', secondary:'—',
    exclusive:'Ningún recurso sólido exclusivo (solo universales), pero es la única fuente de Helium.',
    gases:['Helium','Methane','Nitrogen','Sulfur'], risks:'Niebla dañina, flora extremadamente hostil y terreno traicionero. Ve preparado con buen traje y oxígeno.',
    tips:'Necesitarás Helio para el Nanocarbon Alloy: trae contenedores de gas vacíos y un vehículo resistente.'}
];

// Ayuda para lookup rápido de planetas
const PLANET_MAP = Object.fromEntries(PLANETS.map(p=>[p.id,p]));

/* ---------------- RECURSOS (natural, refinado, gas, compuesto) ---------------- */
const RESOURCES = [
  // ---------- NATURALES ----------
  {id:'compound', name:'Compuesto', en:'Compound', type:'natural', color:'#c9ccd6', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/resources/Icon_Compound.webp', rarity:'Muy común', importance:2,
   found:['sylva','desolo','calidor','vesania','novus','glacio','atrox'],
   obtain:'Se extrae con la Herramienta de Terreno de racimos de esferas grises azuladas, presentes en todos los planetas.',
   process:'No se refina; se usa directamente. También se puede producir 8 unidades con la Centrifugadora de Tierra usando 2 cargas de Soil.',
   centrifuge:true, furnace:false, lab:false,
   recipe:[], tips:'Es de los recursos más usados del juego: guarda siempre un contenedor lleno en la base.',
   trivia:'Antes de la versión 0.4.10221.0 también aparecía en las "spires" (torres) del terreno, eliminadas posteriormente.'},
  {id:'resin', name:'Resina', en:'Resin', type:'natural', color:'#e7c98f', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/resources/Icon_Resin.webp', rarity:'Muy común', importance:2,
   found:['sylva','desolo','calidor','vesania','novus','glacio','atrox'],
   obtain:'Depósitos de color ámbar/dorado en la superficie y cuevas de todos los planetas.',
   process:'No se refina; se usa directamente en fabricación e impresión.',
   centrifuge:false, furnace:false, lab:false,
   recipe:[], tips:'Es el recurso base de casi todas las plataformas e items de impresora pequeña.',
   trivia:'Junto con Compound, formaba parte de las recompensas de las spires antes de que estas fuesen retiradas.'},
  {id:'organic', name:'Orgánico', en:'Organic', type:'natural', color:'#8fdc7a', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/resources/Icon_Organic.webp', rarity:'Común', importance:3,
   found:['sylva','desolo','calidor','vesania','novus','glacio','atrox'],
   obtain:'Se obtiene recolectando flora (plantas, hongos, arbustos) con la Herramienta de Terreno.',
   process:'Puede refinarse en la Fundidora para obtener Carbono, o quemarse en un generador para producir energía (destruye el recurso).',
   centrifuge:false, furnace:true, lab:false,
   recipe:[], tips:'Muy útil como combustible de generadores en las primeras horas de partida, antes de tener paneles solares.',
   trivia:'Distintas plantas de cada planeta producen Orgánico de apariencia distinta, aunque funcionalmente es el mismo recurso.'},
  {id:'quartz', name:'Cuarzo', en:'Quartz', type:'natural', color:'#dcdff0', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/resources/Icon_Quartz.webp', rarity:'Poco común', importance:3,
   found:['sylva','desolo','calidor','vesania','novus','glacio','atrox'],
   obtain:'Cristales prismáticos translúcidos que se encuentran en cuevas y afloramientos rocosos.',
   process:'Se puede usar en bruto o refinar en la Fundidora para obtener Vidrio (Glass).',
   centrifuge:false, furnace:true, lab:false,
   recipe:[], tips:'Guarda algo de Cuarzo sin refinar: lo necesitarás también para el Silicone en el Chemistry Lab.',
   trivia:'Es uno de los pocos recursos naturales que tiene uso tanto en bruto como refinado.'},
  {id:'clay', name:'Arcilla', en:'Clay', type:'natural', color:'#c98a5c', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/resources/Icon_Clay.webp', rarity:'Poco común', importance:2,
   found:['sylva','desolo','calidor','vesania','novus','glacio','atrox'],
   obtain:'Depósitos de tono rojizo-marrón en superficie, normalmente en zonas onduladas.',
   process:'Se refina en la Fundidora para producir Cerámica (Ceramic).',
   centrifuge:false, furnace:true, lab:false,
   recipe:[], tips:'No tiene mucho uso sin refinar: fúndela en cuanto puedas para obtener Cerámica.',
   trivia:'A pesar de encontrarse en los siete planetas, es de los recursos más difíciles de distinguir a simple vista porque se confunde fácilmente con las rocas comunes del terreno.'},
  {id:'laterite', name:'Laterita', en:'Laterite', type:'natural', color:'#c94f3f', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/resources/Icon_Laterite.webp', rarity:'Común', importance:4,
   found:['sylva','desolo','calidor','vesania','novus','glacio','atrox'],
   obtain:'Depósitos cilíndricos rojos y azules bajo la superficie, presentes en casi todos los planetas.',
   process:'Se refina en la Fundidora para obtener Aluminio (Aluminum).',
   centrifuge:false, furnace:true, lab:false,
   recipe:[], tips:'La Plataforma de Comercio da hasta 8 Laterita por 8 Scrap: úsala si te quedas corto.',
   trivia:'Es el único mineral del que se obtiene Aluminio, uno de los metales más utilizados durante toda la partida'},
  {id:'malachite', name:'Malaquita', en:'Malachite', type:'natural', color:'#4fae7a', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/resources/Icon_Malachite.webp', rarity:'Común (Calidor)', importance:4,
   found:['sylva','calidor'],
   obtain:'Vetas de tono verde intenso, muy abundantes en el desierto de Calidor.',
   process:'Se refina en la Fundidora para obtener Cobre (Copper).',
   centrifuge:false, furnace:true, lab:false,
   recipe:[], tips:'Calidor es la mejor fuente si necesitas Cobre para la Chemistry Lab o el Aluminum Alloy.',
   trivia:'Su color viene del mineral real malaquita, un carbonato de cobre.'},
  {id:'hematite', name:'Hematita', en:'Hematite', type:'natural', color:'#8a4a3d', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/resources/Icon_Hematite.webp', rarity:'Común (Novus/Glacio)', importance:4,
   found:['novus','glacio'],
   obtain:'Depósitos de color rojo oscuro que se concentran especialmente en Novus y Glacio.',
   process:'Se refina en la Fundidora para obtener Hierro (Iron).',
   centrifuge:false, furnace:true, lab:false,
   recipe:[], tips:'Consigue grandes cantidades en Novus antes de ir a Glacio, así podrás fabricar Steel sin escasez.',
   trivia:'Nombrada por el mineral real de óxido de hierro que le da su color rojizo.'},
  {id:'titanite', name:'Titanita', en:'Titanite', type:'natural', color:'#d9d2c0', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/resources/Icon_Titanite.webp', rarity:'Poco común', importance:4,
   found:['calidor','vesania','glacio'],
   obtain:'Vetas de tono beige/gris claro, típicas de zonas rocosas y montañosas.',
   process:'Se refina en la Fundidora para obtener Titanio (Titanium).',
   centrifuge:false, furnace:true, lab:false,
   recipe:[], tips:'Es un cuello de botella habitual para el Titanium Alloy: acumula varias unidades antes de empezar la cadena de Nanocarbon.',
   trivia:'El Titanio resultante es uno de los metales más resistentes usados en vehículos avanzados.'},
  {id:'wolframite', name:'Wolframita', en:'Wolframite', type:'natural', color:'#5b5f6b', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/resources/Icon_Wolframite.webp', rarity:'Poco común', importance:3,
   found:['desolo','calidor'],
   obtain:'Depósitos oscuros y densos, comunes en las cuevas de Desolo.',
   process:'Se refina en la Fundidora para obtener Tungsteno (Tungsten).',
   centrifuge:false, furnace:true, lab:false,
   recipe:[], tips:'Necesario para el Chemistry Lab (vía Copper) y para el Tungsten Carbide: trae bastante desde tu primer viaje a Desolo.',
   trivia:'El Tungsteno es el metal con mayor punto de fusión del universo del juego, reflejando su alta densidad en la realidad.'},
  {id:'sphalerite', name:'Esfalerita', en:'Sphalerite', type:'natural', color:'#caa6d9', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/resources/Icon_Sphalerite.webp', rarity:'Poco común', importance:2,
   found:['sylva','desolo'],
   obtain:'Cristales de tono violáceo, frecuentes en las montañas de Sylva y Desolo.',
   process:'Se refina en la Fundidora para obtener Zinc.',
   centrifuge:false, furnace:true, lab:false,
   recipe:[], tips:'El Zinc tiene pocos usos directos de fabricación, pero es útil para investigación temprana de bytes.',
   trivia:'Su nombre proviene del mineral real, principal fuente de zinc en la minería terrestre.'},
  {id:'lithium', name:'Litio', en:'Lithium', type:'natural', color:'#f2a6c9', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/resources/Icon_Lithium.webp', rarity:'Abundante en Vesania y Novus', importance:3,
   found:['vesania','novus'],
   obtain:'Nódulos en forma de fideos rizados rosados y dorados, muy abundantes en Vesania.',
   process:'No se puede refinar; se utiliza en bruto.',
   centrifuge:false, furnace:false, lab:false,
   recipe:[], tips:'Se usa sobre todo en baterías y componentes de investigación: trae bastante de Vesania para toda la partida.',
   trivia:'Es de los pocos metales que el juego trata como "no refinable", a diferencia del resto de minerales.'},
  {id:'ammonium', name:'Amonio', en:'Ammonium', type:'natural', color:'#f5d34a', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/resources/Icon_Ammonium.webp', rarity:'Poco común', importance:4,
   found:['sylva','desolo','calidor','vesania','novus','glacio','atrox'],
   obtain:'Depósitos amarillos brillantes, normalmente cerca de zonas de aterrizaje y cuevas superficiales.',
   process:'No se refina; se usa directamente en el Chemistry Lab.',
   centrifuge:false, furnace:false, lab:false,
   recipe:[], tips:'Es clave para el Hydrazine (combustible de cohetes y cinturones): nunca viajes sin una reserva.',
   trivia:'Es uno de los pocos recursos naturales que alimenta directamente al Chemistry Lab sin pasar por la Fundidora.'},
  {id:'astronium', name:'Astronio', en:'Astronium', type:'natural', color:'#ffdf7e', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/resources/Icon_Astronium.webp', rarity:'Muy raro', importance:3,
   found:['sylva','desolo','calidor','vesania','novus','glacio','atrox'],
   obtain:'Pequeños depósitos brillantes y raros que aparecen en las capas del núcleo exterior de todos los planetas; también puede obtenerse de la Sturdysquash morada durante ciertos eventos.',
   process:'No se refina; se puede intercambiar en la Plataforma de Comercio por un Solid-Fuel Jump Jet, que al triturarse en una Recicladora da 3 Scrap por unidad de Astronio (la mejor tasa del juego).',
   centrifuge:false, furnace:false, lab:false,
   recipe:[], tips:'Guárdalo para canjearlo por Scrap cuando necesites materiales puntuales que no tengas a mano.',
   trivia:'Es de los recursos más difíciles de encontrar en grandes cantidades, ideal como "moneda" de intercambio.'},
  {id:'exo_chip', name:'Chip EXO', en:'EXO Chip', type:'natural', color:'#59d5ff', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/resources/Icon_EXO_Chip.webp', rarity:'Muy raro', importance:5,
   found:['sylva','desolo','calidor','vesania','novus','glacio','atrox'],
   obtain:'No aparece como un depósito mineral. Se obtiene abriendo Cachés EXO (EXO Caches), recuperando Grabadores de Datos de Vehículos (Vehicle Data Recorders) o intercambiando Astronio en la Plataforma de Comercio.',
   process:'No puede refinarse ni fabricarse. Se utiliza directamente como componente para fabricar vehículos, módulos y equipos avanzados.',
   centrifuge:false, furnace:false, lab:false,
   recipe:[],
   tips:'Es un recurso escaso que suele requerir bastante exploración o intercambio para conseguirlo, aunque no es estrictamente finito: siempre puedes obtener más explorando Cachés EXO o intercambiando Astronio.',
   trivia:'Fue añadido con la actualización Automation para sustituir antiguas recetas y fomentar la exploración mediante las Cachés EXO y los restos de vehículos.'},
  {id:'graphite', name:'Grafito', en:'Graphite', type:'natural', color:'#3a3f4a', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/resources/Icon_Graphite.webp', rarity:'Común', importance:4,
   found:['sylva','desolo','calidor','vesania','novus','glacio','atrox'],
   obtain:'Vetas oscuras y laminares presentes en todos los planetas.',
   process:'No se puede refinar; se usa directamente en el Chemistry Lab.',
   centrifuge:false, furnace:false, lab:false,
   recipe:[], tips:'Es la base del Graphene, así que conviene tener siempre unidades de reserva.',
   trivia:'Al igual que Compound y Resin, se catalogó desde el inicio como recurso "no refinable".'},
  {id:'soil', name:'Tierra', en:'Soil', type:'natural', color:'#7a6650', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/resources/Icon_Soil.webp', rarity:'Ilimitado', importance:1,
   found:['sylva','desolo','calidor','vesania','novus','glacio','atrox'],
   obtain:'Se genera automáticamente al excavar terreno con la Herramienta de Terreno.',
   process:'Se introduce en la Centrifugadora de Tierra (Soil Centrifuge), donde el jugador elige qué producir entre Compound, Resin, Organic, Clay, Quartz, Ammonium o Graphite (no depende del bioma).',
   centrifuge:true, furnace:false, lab:false,
   recipe:[], tips:'No necesitas minarla a propósito: se acumula sola mientras excavas para hacer túneles y rampas.',
   trivia:'La Centrifugadora de Tierra fue una de las incorporaciones que redujo la necesidad de "farmear" Compound y Resin a mano.'},

  // ---------- REFINADOS (Fundidora) ----------
  {id:'aluminum', name:'Aluminio', en:'Aluminum', type:'refined', color:'#cfd6de', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/refined/Icon_Aluminum.webp', rarity:'Común', importance:5,
   found:['sylva','desolo','calidor','vesania','novus','glacio','atrox'],
   obtain:'Se obtiene refinando Laterita en la Fundidora (Smelting Furnace).',
   process:'Fundidora: 1 Laterite → 1 Aluminum.',
   centrifuge:false, furnace:false, lab:false,
   recipe:[{id:'laterite',qty:1}],
   tips:'Es de los metales más usados en estructuras y plataformas: mantén siempre una Fundidora activa.',
   trivia:'El logro "Smelteringly Hot" se obtiene precisamente al fundir tu primer Aluminio.'},
  {id:'copper', name:'Cobre', en:'Copper', type:'refined', color:'#e08a4f', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/refined/Icon_Copper.webp', rarity:'Común (Calidor)', importance:4,
   found:['sylva','calidor'],
   obtain:'Se obtiene refinando Malaquita en la Fundidora.',
   process:'Fundidora: 1 Malachite → 1 Copper.',
   centrifuge:false, furnace:false, lab:false,
   recipe:[{id:'malachite',qty:1}],
   tips:'Imprescindible para el Chemistry Lab y el Aluminum Alloy: prioriza un viaje a Calidor pronto.',
   trivia:'Es uno de los primeros refinados que se necesita para acceder a estructuras de nivel medio.'},
  {id:'iron', name:'Hierro', en:'Iron', type:'refined', color:'#8c5a4a', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/refined/Icon_Iron.webp', rarity:'Común (Novus/Glacio)', importance:4,
   found:['novus','glacio'],
   obtain:'Se obtiene refinando Hematita en la Fundidora.',
   process:'Fundidora: 1 Hematite → 1 Iron.',
   centrifuge:false, furnace:false, lab:false,
   recipe:[{id:'hematite',qty:1}],
   tips:'Fundamental para el Steel: acumula un buen stock antes de intentar el Nanocarbon Alloy.',
   trivia:'Combinado con Carbono y Argón en el Chemistry Lab produce Acero (Steel).'},
  {id:'titanium', name:'Titanio', en:'Titanium', type:'refined', color:'#a9a29a', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/refined/Icon_Titanium.webp', rarity:'Poco común', importance:4,
   found:['calidor','vesania','glacio'],
   obtain:'Se obtiene refinando Titanita en la Fundidora.',
   process:'Fundidora: 1 Titanite → 1 Titanium.',
   centrifuge:false, furnace:false, lab:false,
   recipe:[{id:'titanite',qty:1}],
   tips:'Es uno de los materiales más solicitados para vehículos grandes y el Titanium Alloy.',
   trivia:'Aparece con más frecuencia en Glacio, lo que hace de ese planeta un destino habitual a mitad de partida.'},
  {id:'tungsten', name:'Tungsteno', en:'Tungsten', type:'refined', color:'#4c4f57', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/refined/Icon_Tungsten.webp', rarity:'Poco común', importance:3,
   found:['desolo','calidor'],
   obtain:'Se obtiene refinando Wolframita en la Fundidora.',
   process:'Fundidora: 1 Wolframite → 1 Tungsten.',
   centrifuge:false, furnace:false, lab:false,
   recipe:[{id:'wolframite',qty:1}],
   tips:'Base del Tungsten Carbide, un material clave para estructuras de gran resistencia.',
   trivia:'Es de los metales más densos y "raros" de conseguir en las primeras horas.'},
  {id:'zinc', name:'Zinc', en:'Zinc', type:'refined', color:'#8f7aa8', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/refined/Icon_Zinc.webp', rarity:'Poco común', importance:2,
   found:['sylva','desolo'],
   obtain:'Se obtiene refinando Esfalerita en la Fundidora.',
   process:'Fundidora: 1 Sphalerite → 1 Zinc.',
   centrifuge:false, furnace:false, lab:false,
   recipe:[{id:'sphalerite',qty:1}],
   tips:'Con menos recetas directas que otros metales, es buena fuente de bytes tempranos en el Research Chamber.',
   trivia:'Uno de los refinados más "tranquilos" del juego: pocas veces resulta un cuello de botella.'},
  {id:'glass', name:'Vidrio', en:'Glass', type:'refined', color:'#bfe6ea', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/refined/Icon_Glass.webp', rarity:'Poco común', importance:3,
   found:['sylva','desolo','calidor','vesania','novus','glacio','atrox'],
   obtain:'Se obtiene refinando Cuarzo en la Fundidora.',
   process:'Fundidora: 1 Quartz → 1 Glass.',
   centrifuge:false, furnace:false, lab:false,
   recipe:[{id:'quartz',qty:1}],
   tips:'Se usa en varios objetos de investigación y decorativos; no acumula tanta demanda como los metales.',
   trivia:'Comparte origen con el Silicone, que en cambio usa Cuarzo sin refinar.'},
  {id:'ceramic', name:'Cerámica', en:'Ceramic', type:'refined', color:'#e3b98f', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/refined/Icon_Ceramic.webp', rarity:'Poco común', importance:2,
   found:['sylva','desolo','calidor','vesania','novus','glacio','atrox'],
   obtain:'Se obtiene refinando Arcilla en la Fundidora.',
   process:'Fundidora: 1 Clay → 1 Ceramic.',
   centrifuge:false, furnace:false, lab:false,
   recipe:[{id:'clay',qty:1}],
   tips:'Poco exigida en recetas avanzadas, pero útil para completar el catálogo de investigación temprano.',
   trivia:'A diferencia de otros refinados, la Cerámica tiene pocas recetas directas que la demanden en el juego tardío.'},
  {id:'carbon', name:'Carbono', en:'Carbon', type:'refined', color:'#2c2f36', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/refined/Icon_Carbon.webp', rarity:'Común', importance:5,
   found:['sylva','desolo','calidor','vesania','novus','glacio','atrox'],
   obtain:'Se obtiene refinando Orgánico en la Fundidora.',
   process:'Fundidora: 1 Organic → 1 Carbon.',
   centrifuge:false, furnace:false, lab:false,
   recipe:[{id:'organic',qty:1}],
   tips:'Es ingrediente de Plastic, Steel, Explosive Powder y Tungsten Carbide: nunca te quedes sin Orgánico de reserva.',
   trivia:'También puede quemarse en un generador para producir energía, aunque destruye el recurso en el proceso.'},

  // ---------- GASES (Condensador Atmosférico) ----------
  {id:'argon', name:'Argón', en:'Argon', type:'gas', color:'#7ab8ff', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/atmospheric/Icon_Argon.webp', rarity:'Poco común (Vesania y Glacio)', importance:4,
   found:['vesania','glacio'],
   obtain:'Se recolecta con el Condensador Atmosférico en la atmósfera de Vesania y Glacio.',
   process:'Condensador Atmosférico (Atmospheric Condenser).',
   centrifuge:false, furnace:false, lab:false,
   recipe:[], tips:'Es la razón principal para instalar una base en Glacio: sin Argón no hay Steel ni Titanium Alloy.',
   trivia:'Es uno de los gases más escasos del juego junto al Helio, y clave exclusiva para fabricar Acero (Steel).'},
  {id:'helium', name:'Helio', en:'Helium', type:'gas', color:'#ffe08a', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/atmospheric/Icon_Helium.webp', rarity:'Exclusivo de Atrox', importance:5,
   found:['atrox'],
   obtain:'Solo se encuentra en la atmósfera de Atrox; requiere Condensador Atmosférico.',
   process:'Condensador Atmosférico.',
   centrifuge:false, furnace:false, lab:false,
   recipe:[], tips:'Imprescindible para el Nanocarbon Alloy: planifica bien tu viaje a Atrox, ya que es el planeta más peligroso.',
   trivia:'Es el único recurso auténticamente exclusivo de un solo planeta en todo el juego.'},
  {id:'hydrogen', name:'Hidrógeno', en:'Hydrogen', type:'gas', color:'#c9e8ff', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/atmospheric/Icon_Hydrogen.webp', rarity:'Común (varios planetas)', importance:5,
   found:['sylva','calidor','vesania','novus'],
   obtain:'Disponible en la atmósfera de Sylva, Calidor, Vesania y Novus mediante Condensador Atmosférico.',
   process:'Condensador Atmosférico.',
   centrifuge:false, furnace:false, lab:false,
   recipe:[], tips:'Base del Hydrazine, el combustible de cohetes y VTOL: instala tu primer condensador en Sylva.',
   trivia:'Aunque en el desarrollo se pensó en obtenerlo del hielo/agua, esa mecánica nunca llegó al juego final.'},
  {id:'methane', name:'Metano', en:'Methane', type:'gas', color:'#8fd6a0', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/atmospheric/Icon_Methane.webp', rarity:'Común (varios planetas)', importance:3,
   found:['novus','atrox'],
   obtain:'Presente en la atmósfera de Novus y Atrox.',
   process:'Condensador Atmosférico.',
   centrifuge:false, furnace:false, lab:false,
   recipe:[], tips:'Necesario para el Silicone junto con Resin y Quartz.',
   trivia:'Es el gas atmosférico con mayor valor de Bytes por unidad entre los que alcanzan una concentración del 100% en el Condensador Atmosférico.'},
  {id:'nitrogen', name:'Nitrógeno', en:'Nitrogen', type:'gas', color:'#a0c9ff', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/atmospheric/Icon_Nitrogen.webp', rarity:'Común (varios planetas)', importance:4,
   found:['sylva','vesania','atrox'],
   obtain:'Presente en la atmósfera de Sylva, Vesania y Atrox.',
   process:'Condensador Atmosférico.',
   centrifuge:false, furnace:false, lab:false,
   recipe:[], tips:'Clave para el Titanium Alloy: recoge bastante mientras estés en Sylva.',
   trivia:'Junto al Hidrógeno, es uno de los dos gases presentes en tu planeta natal.'},
  {id:'sulfur', name:'Azufre', en:'Sulfur', type:'gas', color:'#f5e05a', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/atmospheric/Icon_Sulfur.webp', rarity:'Poco común', importance:3,
   found:['calidor','atrox'],
   obtain:'Presente en la atmósfera de Calidor y Atrox.',
   process:'Condensador Atmosférico.',
   centrifuge:false, furnace:false, lab:false,
   recipe:[], tips:'Necesario para el Explosive Powder: si vas a fabricar dinamita en masa, trae varios tanques desde Calidor.',
   trivia:'Es uno de los gases menos comunes junto al Argón y el Helio.'},

  // ---------- COMPUESTOS (Chemistry Lab) ----------
  {id:'rubber', name:'Caucho', en:'Rubber', type:'composite', color:'#3d3f46', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/chemistry/Icon_Rubber.webp', rarity:'Fabricado', importance:4,
   found:[],
   obtain:'Se sintetiza en el Chemistry Lab combinando recursos naturales.',
   process:'Chemistry Lab: 1 Organic + 1 Resin → 1 Rubber.',
   centrifuge:false, furnace:false, lab:true,
   recipe:[{id:'organic',qty:1},{id:'resin',qty:1}],
   tips:'Es de los primeros compuestos que se desbloquean; imprescindible para Small y Medium Shredder.',
   trivia:'Es el único compuesto que no requiere ningún gas en su receta.'},
  {id:'plastic', name:'Plástico', en:'Plastic', type:'composite', color:'#e7e9ef', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/chemistry/Icon_Plastic.webp', rarity:'Fabricado', importance:5,
   found:[],
   obtain:'Se sintetiza en el Chemistry Lab a partir de Compound y Carbon.',
   process:'Chemistry Lab: 1 Compound + 1 Carbon → 1 Plastic.',
   centrifuge:false, furnace:false, lab:true,
   recipe:[{id:'compound',qty:1},{id:'carbon',qty:1}],
   tips:'Muy demandado en estructuras y vehículos: automatiza su producción en cuanto tengas Auto Arm.',
   trivia:'Al usar solo dos ingredientes muy comunes, suele ser el compuesto más fácil de producir en masa.'},
  {id:'aluminum_alloy', name:'Aleación de Aluminio', en:'Aluminum Alloy', type:'composite', color:'#d7dbe3', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/chemistry/Icon_Aluminum_Alloy.webp', rarity:'Fabricado', importance:4,
   found:[],
   obtain:'Se sintetiza en el Chemistry Lab combinando dos metales refinados.',
   process:'Chemistry Lab: 1 Aluminum + 1 Copper → 1 Aluminum Alloy.',
   centrifuge:false, furnace:false, lab:true,
   recipe:[{id:'aluminum',qty:1},{id:'copper',qty:1}],
   tips:'Se usa en estructuras de plataforma media; asegura suministro constante de Aluminio y Cobre.',
   trivia:'Es el único compuesto hecho exclusivamente de dos metales refinados, sin gas ni recurso natural.'},
  {id:'tungsten_carbide', name:'Carburo de Tungsteno', en:'Tungsten Carbide', type:'composite', color:'#4a4d55', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/chemistry/Icon_Tungsten_Carbide.webp', rarity:'Fabricado', importance:3,
   found:[],
   obtain:'Se sintetiza en el Chemistry Lab a partir de Carbon y Tungsten.',
   process:'Chemistry Lab: 1 Carbon + 1 Tungsten → 1 Tungsten Carbide.',
   centrifuge:false, furnace:false, lab:true,
   recipe:[{id:'carbon',qty:1},{id:'tungsten',qty:1}],
   tips:'Usado en piezas de gran resistencia estructural en la mitad-final del árbol tecnológico.',
   trivia:'Comparte el Carbono como ingrediente con Plastic, Steel y Explosive Powder.'},
  {id:'graphene', name:'Grafeno', en:'Graphene', type:'composite', color:'#5c5f66', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/chemistry/Icon_Graphene.webp', rarity:'Fabricado', importance:5,
   found:[],
   obtain:'Se sintetiza en el Chemistry Lab a partir de Graphite y Hydrazine.',
   process:'Chemistry Lab: 1 Graphite + 1 Hydrazine → 1 Graphene.',
   centrifuge:false, furnace:false, lab:true,
   recipe:[{id:'graphite',qty:1},{id:'hydrazine',qty:1}],
   tips:'Paso obligatorio hacia Diamond y Titanium Alloy: produce Hydrazine en cantidad antes de empezar esta cadena.',
   trivia:'Es uno de los compuestos "intermedios" más usados, ya que alimenta a otros dos compuestos distintos.'},
  {id:'diamond', name:'Diamante', en:'Diamond', type:'composite', color:'#eaf6ff', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/chemistry/Icon_Diamond.webp', rarity:'Fabricado (raro)', importance:3,
   found:[],
   obtain:'Se sintetiza en el Chemistry Lab a partir de dos unidades de Graphene.',
   process:'Chemistry Lab: 2 Graphene → 1 Diamond.',
   centrifuge:false, furnace:false, lab:true,
   recipe:[{id:'graphene',qty:2}],
   tips:'Al requerir 2 Graphene, es de los compuestos más caros de producir; resérvalo para objetos de investigación de alto valor.',
   trivia:'Es el único compuesto cuya receta usa un solo ingrediente (aunque en cantidad doble).'},
  {id:'hydrazine', name:'Hidrazina', en:'Hydrazine', type:'composite', color:'#ffb066', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/chemistry/Icon_Hydrazine.webp', rarity:'Fabricado', importance:5,
   found:[],
   obtain:'Se sintetiza en el Chemistry Lab combinando Ammonium con Hydrogen.',
   process:'Chemistry Lab: 2 Ammonium + 1 Hydrogen → 1 Hydrazine.',
   centrifuge:false, furnace:false, lab:true,
   recipe:[{id:'ammonium',qty:2},{id:'hydrogen',qty:1}],
   tips:'Combustible de cohetes, VTOL y mochilas propulsoras: mantén siempre unidades de reserva antes de despegar.',
   trivia:'Es también uno de los ingredientes necesarios para fabricar Graphene, por lo que su demanda es doble.'},
  {id:'silicone', name:'Silicona', en:'Silicone', type:'composite', color:'#e5e0d8', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/chemistry/Icon_Silicone.webp', rarity:'Fabricado', importance:3,
   found:[],
   obtain:'Se sintetiza en el Chemistry Lab combinando tres ingredientes distintos.',
   process:'Chemistry Lab: 1 Resin + 1 Quartz + 1 Methane → 1 Silicone.',
   centrifuge:false, furnace:false, lab:true,
   recipe:[{id:'resin',qty:1},{id:'quartz',qty:1},{id:'methane',qty:1}],
   tips:'Es el único compuesto con tres ingredientes distintos: prepárate para hacer más viajes de recolección.',
   trivia:'Su icono recuerda a un tubo de gel, en referencia a las siliconas reales usadas como selladores.'},
  {id:'explosive_powder', name:'Pólvora Explosiva', en:'Explosive Powder', type:'composite', color:'#7a2b25', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/chemistry/Icon_Explosive_Powder.webp', rarity:'Fabricado', importance:3,
   found:[],
   obtain:'Se sintetiza en el Chemistry Lab a partir de Carbon y Sulfur.',
   process:'Chemistry Lab: 2 Carbon + 1 Sulfur → 1 Explosive Powder.',
   centrifuge:false, furnace:false, lab:true,
   recipe:[{id:'carbon',qty:2},{id:'sulfur',qty:1}],
   tips:'Se usa para fabricar dinamita, útil para abrir grandes cavidades rápidamente en el terreno.',
   trivia:'Visualmente aparece como una versión oscura y rojiza del Ammonium.'},
  {id:'steel', name:'Acero', en:'Steel', type:'composite', color:'#8892a0', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/chemistry/Icon_Steel.webp', rarity:'Fabricado', importance:5,
   found:[],
   obtain:'Se sintetiza en el Chemistry Lab combinando Carbon, Iron y Argon.',
   process:'Chemistry Lab: 1 Carbon + 1 Iron + 1 Argon → 1 Steel.',
   centrifuge:false, furnace:false, lab:true,
   recipe:[{id:'carbon',qty:1},{id:'iron',qty:1},{id:'argon',qty:1}],
   tips:'Ingrediente clave del Nanocarbon Alloy: monta una base en Glacio para producirlo cerca de la fuente de Argón.',
   trivia:'Es uno de los compuestos más solicitados para estructuras de almacenamiento de gran tamaño.'},
  {id:'titanium_alloy', name:'Aleación de Titanio', en:'Titanium Alloy', type:'composite', color:'#b7bcc4', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/chemistry/Icon_Titanium_Alloy.webp', rarity:'Fabricado', importance:5,
   found:[],
   obtain:'Se sintetiza en el Chemistry Lab combinando Titanium, Graphene y Nitrogen.',
   process:'Chemistry Lab: 1 Titanium + 1 Graphene + 1 Nitrogen → 1 Titanium Alloy.',
   centrifuge:false, furnace:false, lab:true,
   recipe:[{id:'titanium',qty:1},{id:'graphene',qty:1},{id:'nitrogen',qty:1}],
   tips:'Uno de los compuestos con cadena de producción más larga; planifica varios viajes entre Glacio y Sylva.',
   trivia:'Es el penúltimo eslabón antes de poder fabricar Nanocarbon Alloy, el material más avanzado del juego.'},
  {id:'nanocarbon_alloy', name:'Aleación de Nanocarbono', en:'Nanocarbon Alloy', type:'composite', color:'#2e3238', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/chemistry/Icon_Nanocarbon_Alloy.webp', rarity:'Fabricado (endgame)', importance:5,
   found:[],
   obtain:'Se sintetiza en el Chemistry Lab combinando Steel, Titanium Alloy y Helium: el compuesto más avanzado del juego.',
   process:'Chemistry Lab: 1 Steel + 1 Titanium Alloy + 1 Helium → 1 Nanocarbon Alloy.',
   centrifuge:false, furnace:false, lab:true,
   recipe:[{id:'steel',qty:1},{id:'titanium_alloy',qty:1},{id:'helium',qty:1}],
   tips:'Requiere visitar como mínimo Sylva o Vesania (Hidrógeno/Nitrógeno), Glacio (Hierro/Titanio/Argón) y Atrox (Helio). Planea bien la ruta.',
   trivia:'El logro "Composite Perfection" se obtiene al refinar tu primera unidad de este material.'}
];

const RESOURCE_MAP = Object.fromEntries(RESOURCES.map(r=>[r.id,r]));

/* ---------------- OBJETOS IMPRIMIBLES / PLATAFORMAS / ESTRUCTURAS ----------------
   Los materiales de esta sección están anclados a dos fuentes cruzadas:
   1) Las páginas oficiales de "Compound" y "Resin" de la wiki (listas reales de
      "usado para fabricar"), que confirman en qué impresora y en qué objeto
      participa cada recurso.
   2) La guía de crafteo de la comunidad (Astroneer 0.10.2.0 "Crafting Update"),
      usada como referencia de cantidades cuando la wiki actual no detalla el número.
   Las cantidades pueden variar levemente entre parches: revisa la impresora
   in-game si algo no cuadra exactamente con tu versión. */
const OBJECTS = [
  // ---- Mochila (Backpack Printer) — gratis, disponible desde el minuto uno ----
  {id:'tether', name:'Amarre (Tether)', en:'Tether', cat:'soporte vital', printer:'Mochila', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Tether.webp',
   materials:[{id:'compound',qty:1}], desc:'Cable que suministra oxígeno y energía desde la base o el traje a zonas alejadas.',
   uses:'Herramienta esencial de exploración: marca tu camino y te mantiene con vida en cuevas.',
   tips:'Colócalos en línea recta y no muy alejados entre sí para asegurar un flujo constante de oxígeno.'},
  {id:'canister', name:'Contenedor (Canister)', en:'Canister', cat:'almacenamiento', printer:'Mochila',
   materials:[{id:'resin',qty:1}], desc:'Pieza de terreno moldeable: crea paredes, rampas y puentes con la Herramienta de Terreno.',
   uses:'Imprescindible para construir rampas de acceso a tu base y sellar cuevas.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Small_Canister.webp',
   tips:'Lleva siempre 2-3 en tu mochila cuando explores: te sacan de apuros en terrenos imposibles.'},
  {id:'oxygen_filter', name:'Filtro de Oxígeno', en:'Oxygen Filter', cat:'soporte vital', printer:'Mochila', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Oxygen_Tank.webp',
   materials:[{id:'resin',qty:1}], desc:'Recarga instantánea de oxígeno para tu traje.',
   uses:'Salvavidas de emergencia cuando te quedas sin tethers ni vehículo cerca.',
   tips:'Lleva siempre uno de reserva en tu mochila antes de adentrarte en cuevas profundas.'},
  {id:'beacon', name:'Baliza (Beacon)', en:'Beacon', cat:'exploración', printer:'Mochila', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Beacon.webp',
   materials:[{id:'quartz',qty:1}], desc:'Marca un punto en el mapa y el cielo para encontrarlo desde lejos.',
   uses:'Marca bases secundarias, naufragios o yacimientos importantes en otros planetas.',
   tips:'Cámbiale el color para diferenciar bases de recursos, de tránsito o de emergencia.'},
  {id:'work_light', name:'Foco de Trabajo', en:'Work Light', cat:'utilidad', printer:'Mochila', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Worklight.webp',
   materials:[{id:'copper',qty:1}], desc:'Ilumina el área de trabajo, útil en cuevas oscuras o de noche.',
   uses:'Acompaña casi cualquier base temprana para no quedarte a oscuras.',
   tips:'Combínalo con un Small Generator para tener luz constante en tu primer campamento.'},
  {id:'small_generator', name:'Generador Pequeño', en:'Small Generator', cat:'energía', printer:'Mochila', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Generator.webp',
   materials:[{id:'compound',qty:1}], desc:'Quema Orgánico (o Carbono) para producir energía de forma constante.',
   uses:'Fuente de energía fiable antes de tener paneles solares o eólicos suficientes.',
   tips:'Guarda algo de Orgánico siempre a mano como "batería de emergencia" para la noche.'},
  {id:'small_oxygen_tank', name:'Tanque de Oxígeno Pequeño', en:'Small Oxygen Tank', cat:'soporte vital', printer:'Mochila', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Oxygen_Tank.webp',
   materials:[{id:'glass',qty:1}], desc:'Amplía la reserva de oxígeno del traje del astronauta.',
   uses:'Fundamental para expediciones largas lejos de tethers o vehículos con oxígeno.',
   tips:'Combínalo con tethers largos para no quedarte sin aire en cuevas profundas.'},
  {id:'small_solar', name:'Panel Solar Pequeño', en:'Small Solar Panel', cat:'energía', printer:'Mochila', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Solar.webp',
   materials:[{id:'copper',qty:1}], desc:'Genera energía durante el día; su rendimiento depende del ciclo solar del planeta.',
   uses:'Ideal en Calidor y Sylva, donde el ciclo diurno es más largo y constante.',
   tips:'En Glacio o Atrox, con ciclos día/noche largos y poca luz efectiva, complementa con baterías o eólicas.'},
  {id:'small_wind', name:'Turbina Eólica Pequeña', en:'Small Wind Turbine', cat:'energía', printer:'Mochila', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Wind_Turbine.webp',
   materials:[{id:'glass',qty:1}], desc:'Genera energía a partir del viento; rendimiento variable según el planeta y la hora.',
   uses:'Muy eficaz en Novus, con su ciclo día/noche corto, y en general como energía complementaria.',
   tips:'Combínala con un panel solar para tener cobertura energética tanto de día como de noche.'},
  {id:'power_cell', name:'Célula de Energía', en:'Power Cell', cat:'energía', printer:'Mochila', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Power_Cells.webp',
   materials:[{id:'zinc',qty:1}], desc:'Batería portátil de un solo uso que puedes llevar en cualquier ranura.',
   uses:'Backup rápido de energía para tu traje o pequeños vehículos.',
   tips:'Útil para expediciones cortas donde no quieres cargar con un generador completo.'},
  {id:'small_battery', name:'Batería Pequeña', en:'Small Battery', cat:'energía', printer:'Mochila', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Battery.webp',
   materials:[{id:'lithium',qty:1}], desc:'Almacena energía sobrante para usarla cuando la producción cae.',
   uses:'Complementa paneles solares y turbinas en bases pequeñas.',
   tips:'El Litio de Vesania es la mejor fuente para producir estas baterías en cadena.'},
  {id:'dynamite', name:'Dinamita', en:'Dynamite', cat:'herramienta', printer:'Mochila', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Dynamite.webp',
   materials:[{id:'explosive_powder',qty:1}], desc:'Explosivo que abre grandes cavidades en el terreno al instante.',
   uses:'Muy útil para minería rápida o para despejar el camino de un vehículo atascado.',
   tips:'Aléjate bien antes de detonarla: el radio de explosión es mayor de lo que parece.'},

  // ---- Impresora Pequeña (Small Printer) ----
  {id:'medium_storage', name:'Almacenamiento Mediano', en:'Medium Storage', cat:'almacenamiento', printer:'Impresora Pequeña',
   materials:[{id:'resin',qty:2}], desc:'Módulo de almacenamiento con varias ranuras para nuggets sueltos.',
   uses:'Reduce el desorden de tu base agrupando recursos en un solo módulo.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Storage.webp',
   tips:'Colócalo sobre un Large Platform B para que reciba automáticamente lo que sale de la Fundidora.'},
  {id:'medium_platform_a', name:'Plataforma Mediana A', en:'Medium Platform A', cat:'estructura', printer:'Impresora Pequeña',
   materials:[{id:'resin',qty:1}], desc:'Base modular para colocar módulos medianos como el Research Chamber o la Fundidora.',
   uses:'El "suelo" sobre el que se construye la mayoría de bases pequeñas.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Platforms.webp',
   tips:'Es de las piezas más baratas: no dudes en imprimir varias para expandirte rápido.'},
  {id:'medium_platform_b', name:'Plataforma Mediana B', en:'Medium Platform B', cat:'estructura', printer:'Impresora Pequeña',
   materials:[{id:'resin',qty:2}], desc:'Variante de plataforma mediana con ranuras laterales extra.',
   uses:'Perfecta para colocar Almacenamiento Mediano a los lados mientras procesas recursos arriba.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Platforms.webp',
   tips:'Combínala con la Fundidora encima y un Medium Storage a cada lado para una mini fábrica compacta.'},
  {id:'medium_shredder', name:'Trituradora Mediana', en:'Medium Shredder', cat:'estructura', printer:'Impresora Pequeña',
   materials:[{id:'iron',qty:2}], desc:'Recicla objetos pequeños y medianos en Scrap.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Shredder.webp',
   uses:'Libera espacio e inventario recuperando parte del valor de objetos que ya no usas.',
   tips:'Muy útil para deshacerte de duplicados de exploración sin perder todo su valor.'},
  {id:'rover_seat', name:'Asiento de Rover', en:'Rover Seat', cat:'vehiculo', printer:'Impresora Pequeña',
   materials:[{id:'compound',qty:2}], desc:'Asiento adicional para vehículos, permite llevar más de un astronauta.',
   uses:'Convierte cualquier rover en transporte de varios pasajeros.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Rover_Seat.webp',
   tips:'Muy barato de fabricar: lleva siempre uno de repuesto en el inventario.'},
  {id:'medium_generator', name:'Generador Mediano', en:'Medium Generator', cat:'energía', printer:'Impresora Pequeña',
   materials:[{id:'tungsten',qty:1},{id:'aluminum',qty:1}], desc:'Genera más energía que el Small Generator quemando Carbono u Orgánico.',
   uses:'Ideal para bases medianas con varias impresoras y estructuras activas a la vez.',  icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Generator.webp',
   tips:'Usa Carbono en vez de Orgánico: rinde mucha más energía por nugget.'},
  {id:'medium_solar', name:'Panel Solar Mediano', en:'Medium Solar Panel', cat:'energía', printer:'Impresora Pequeña',
   materials:[{id:'glass',qty:1},{id:'copper',qty:1}], desc:'Versión de mayor capacidad del panel solar, ideal para bases fijas.',
   uses:'Cubre el consumo de estructuras como la Fundidora o el Chemistry Lab durante el día.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Solar.webp',
   tips:'Combínalo con una Batería Mediana para no perder producción durante la noche.'},
  {id:'medium_wind', name:'Turbina Eólica Mediana', en:'Medium Wind Turbine', cat:'energía', printer:'Impresora Pequeña',
   materials:[{id:'ceramic',qty:1},{id:'glass',qty:1}], desc:'Versión de mayor capacidad de la turbina eólica.',
   uses:'Muy eficaz en planetas ventosos o de ciclo día/noche corto como Novus.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Wind_Turbine.webp',
   tips:'Colócala en zonas elevadas para captar más viento.'},
  {id:'medium_battery', name:'Batería Mediana', en:'Medium Battery', cat:'energía', printer:'Impresora Pequeña',
   materials:[{id:'zinc',qty:1},{id:'lithium',qty:1}], desc:'Almacena energía sobrante para usarla cuando la producción cae (de noche o sin viento).',
   uses:'Evita que tu base se quede sin energía en los "valles" de producción solar o eólica.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Battery.webp',
   tips:'En planetas de ciclo largo como Glacio, necesitarás varias baterías conectadas en cadena.'},
  {id:'winch', name:'Cabrestante (Winch)', en:'Winch', cat:'utilidad', printer:'Impresora Pequeña',
   materials:[{id:'rubber',qty:1},{id:'tungsten',qty:1}], desc:'Cable de remolque que engancha vehículos o carga suelta.',
   uses:'Salva vehículos volcados o atascados en pendientes pronunciadas.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Winch.webp',
   tips:'Llévalo en cualquier rover de exploración: te ahorra caminatas largas de rescate.'},
  {id:'drill_head', name:'Cabezal de Perforación', en:'Drill Head', cat:'vehiculo', printer:'Impresora Pequeña',
   materials:[{id:'ceramic',qty:1},{id:'tungsten_carbide',qty:1}], desc:'Se instala en vehículos para perforar terreno automáticamente al conducir.',
   uses:'Excavación rápida de túneles y rampas sin usar la Herramienta de Terreno a mano.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Drill.webp',
   tips:'Combínalo con un Auto Extractor cercano para automatizar toda una operación minera.'},
  {id:'solid_fuel_thruster', name:'Propulsor de Combustible Sólido', en:'Solid-Fuel Thruster', cat:'vehiculo', printer:'Impresora Pequeña',
   materials:[{id:'ammonium',qty:1},{id:'aluminum',qty:1}], desc:'Motor básico de cohete para el primer vuelo interplanetario.',
   uses:'Imprescindible para tu primer despegue: sin él no puedes salir de Sylva.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Thruster.webp',
   tips:'Lleva siempre uno de repuesto guardado en la mochila para el viaje de vuelta.'},
  {id:'hydrazine_thruster', name:'Propulsor de Hidrazina', en:'Hydrazine Thruster', cat:'vehiculo', printer:'Impresora Pequeña',
   materials:[{id:'titanium_alloy',qty:1},{id:'tungsten',qty:1}], desc:'Motor de cohete avanzado, más eficiente que el de combustible sólido.',
   uses:'Vuelos interplanetarios más rápidos y con mayor capacidad de carga.',  icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Thruster.webp',
   tips:'Requiere Hidrazina como combustible: asegura una buena producción antes de depender de él.'},

  // ---- Impresora Mediana (Medium Printer) ----
  {id:'large_platform_a', name:'Plataforma Grande A', en:'Large Platform A', cat:'estructura', printer:'Impresora Mediana',
   materials:[{id:'resin',qty:2}], desc:'Base modular de mayor tamaño para estructuras medianas y grandes.',
   uses:'Soporte típico para el Research Chamber, la Fundidora o el Chemistry Lab.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Platforms.webp',
   tips:'Déjala fija cerca de tu Vehicle Bay para que sea el corazón de tu base principal.'},
  {id:'large_platform_b', name:'Plataforma Grande B', en:'Large Platform B', cat:'estructura', printer:'Impresora Mediana',
   materials:[{id:'resin',qty:3}], desc:'Variante con dos ranuras laterales, ideales para almacenamiento auxiliar.',
   uses:'Muy usada para crear estaciones de refinado con almacenamiento incorporado a los lados.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Platforms.webp',
   tips:'Coloca un Medium Storage en cada ranura lateral para que la Fundidora se autoalimente.'},
  {id:'large_platform_c', name:'Plataforma Grande C', en:'Large Platform C', cat:'estructura', printer:'Impresora Mediana',
   materials:[{id:'iron',qty:3}], desc:'Variante reforzada de plataforma grande, pensada para estructuras pesadas.',
   uses:'Base sólida para instalaciones de automatización o líneas de producción avanzadas.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Platforms.webp',
   tips:'Resérvala para tu base principal, ya que su coste en Hierro es más alto que las otras plataformas.'},
  {id:'research_chamber', name:'Cámara de Investigación', en:'Research Chamber', cat:'estructura', printer:'Impresora Mediana',
   materials:[{id:'resin',qty:1},{id:'compound',qty:2}], desc:'Convierte recursos y objetos de investigación en Bytes, la moneda de investigación del juego.',
   uses:'Desbloquea nuevas recetas e impresoras a medida que gastas Bytes en el árbol tecnológico.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Research.webp',
   tips:'Investigar objetos de exploración (samples, cápsulas) da muchos más bytes que investigar recursos crudos.'},
  {id:'smelting_furnace', name:'Fundidora', en:'Smelting Furnace', cat:'estructura', printer:'Impresora Mediana',
   materials:[{id:'resin',qty:2},{id:'compound',qty:1}], desc:'Refina recursos naturales en recursos refinados (p. ej. Laterita en Aluminio).',
   uses:'Imprescindible desde el inicio: sin ella no se puede acceder a casi ningún metal refinado.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/menu/Icon_Smelting_Furnace.webp',
   tips:'Colócala junto a un contenedor de recursos naturales para automatizar el refinado con Auto Arm más adelante.'},
  {id:'soil_centrifuge', name:'Centrifugadora de Tierra', en:'Soil Centrifuge', cat:'estructura', printer:'Impresora Mediana',
   materials:[{id:'aluminum',qty:1},{id:'compound',qty:2}], desc:'Separa la Tierra (Soil) recogida al excavar en Compound, Resin, Organic, Clay, Quartz y Graphite.',
   uses:'Reduce muchísimo la necesidad de "farmear" Compound y Resin a mano.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Soil_Centrifuge.webp',
   tips:'Conéctala a un Auto Arm y un Medium Storage para reciclar automáticamente toda la tierra que generes al excavar.'},
  {id:'chemistry_lab', name:'Laboratorio Químico', en:'Chemistry Lab', cat:'estructura', printer:'Impresora Mediana',
   materials:[{id:'tungsten',qty:1},{id:'glass',qty:1},{id:'ceramic',qty:1}], desc:'Combina pares (o tríos) de recursos, a veces con un gas, para crear recursos compuestos.',
   uses:'Puerta de entrada a Rubber, Plastic, Hydrazine, Steel y el resto de compuestos avanzados.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/menu/Icon_Chemistry_Lab.webp',
   tips:'Desbloquearlo cuesta 1600 Bytes en el Research Chamber; úsalo una vez para el logro "Lab Rat".'},
  {id:'atmospheric_condenser', name:'Condensador Atmosférico', en:'Atmospheric Condenser', cat:'estructura', printer:'Impresora Mediana',
   materials:[{id:'iron',qty:1},{id:'glass',qty:1},{id:'plastic',qty:1}], desc:'Condensa la atmósfera del planeta en gases utilizables en la Chemistry Lab.',
   uses:'Necesario para obtener cualquier gas: Hydrogen, Nitrogen, Methane, Argon, Sulfur o Helium.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/menu/Icon_Atmospheric_Condenser.webp',
   tips:'Colócalo en zonas altas para mayor eficiencia y conéctalo a contenedores de gas vacíos.'},
  {id:'trade_platform', name:'Plataforma de Comercio', en:'Trade Platform', cat:'estructura', printer:'Impresora Mediana',
   materials:[{id:'compound',qty:1},{id:'tungsten',qty:1},{id:'iron',qty:1}], desc:'Intercambia recursos por Scrap, y Scrap por otros recursos, a distintas tasas.',
   uses:'Ideal para conseguir de urgencia el recurso que te falte, o para deshacerte de excedentes.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Trade_Platform.webp',
   tips:'Astronio da la mejor tasa de conversión a Scrap: consérvalo para emergencias de fabricación.'},
  {id:'large_shredder', name:'Trituradora Grande', en:'Large Shredder', cat:'estructura', printer:'Impresora Mediana',
   materials:[{id:'iron',qty:2},{id:'tungsten_carbide',qty:1}], desc:'Versión más grande de la trituradora, capaz de reciclar vehículos y estructuras completas.',
   uses:'Perfecta para deshacerte de rovers o remolques que ya no necesites.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Shredder.webp',
   tips:'Colócala cerca del garaje: reciclar vehículos viejos ayuda mucho a conseguir Scrap para el Trade Platform.'},
  {id:'exo_request', name:'Plataforma de Solicitud EXO', en:'EXO Request Platform', cat:'estructura', printer:'Impresora Mediana',
   materials:[{id:'plastic',qty:1}], desc:'Permite solicitar misiones y recompensas de la organización EXO a cambio de recursos.',
   uses:'Fuente adicional de Bytes y objetos únicos completando misiones.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Trade_Platform.webp',
   tips:'Revisa las misiones activas regularmente: algunas piden materiales que ya tienes de sobra.'},

  // ---- Impresora Grande (Large Printer) ----
  {id:'extra_large_platform_a', name:'Plataforma Extra Grande A', en:'Extra-Large Platform A', cat:'estructura', printer:'Impresora Grande',
   materials:[{id:'iron',qty:4}], desc:'La mayor base modular del juego, pensada para instalaciones industriales.',
   uses:'Soporte de proyectos a gran escala: líneas de producción completas o zonas de lanzamiento.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Platforms.webp',
   tips:'Resérvala para tu base principal: su coste en Hierro es considerable.'},
  {id:'extra_large_platform_b', name:'Plataforma Extra Grande B', en:'Extra-Large Platform B', cat:'estructura', printer:'Impresora Grande',
   materials:[{id:'resin',qty:2},{id:'iron',qty:2}], desc:'Variante de la plataforma extra grande con ranuras adicionales.',
   uses:'Ideal para bases avanzadas con múltiples silos y estructuras de automatización.',  icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Platforms.webp',
   tips:'Combínala con Extra Large Storage para tener las mayores reservas de recursos del juego.'},
  {id:'large_storage', name:'Almacenamiento Grande', en:'Large Storage', cat:'almacenamiento', printer:'Impresora Grande',
   materials:[{id:'ceramic',qty:3}], desc:'Módulo de almacenamiento de mayor capacidad que el Medium Storage.',
   uses:'Ideal para acopiar grandes cantidades de un recurso antes de un proyecto grande (como un cohete).',
   icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Storage.webp',
   tips:'Colócalo cerca de tu Fundidora o Chemistry Lab para minimizar el transporte manual.'},
  {id:'extra_large_storage', name:'Almacenamiento Extra Grande', en:'Extra-Large Storage', cat:'almacenamiento', printer:'Impresora Grande',
   materials:[{id:'iron',qty:2},{id:'steel',qty:2}], desc:'El mayor módulo de almacenamiento disponible, con numerosas ranuras.',
   uses:'Reserva masiva de recursos para bases de producción industrial o proyectos endgame.',
   icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Storage.webp',
   tips:'Apóyalo contra una pared para poder acceder a todas sus caras cómodamente.'},
  {id:'crane', name:'Grúa (Crane)', en:'Crane', cat:'utilidad', printer:'Impresora Grande',
   materials:[{id:'titanium',qty:1},{id:'silicone',qty:1},{id:'steel',qty:1}], desc:'Brazo mecánico que levanta y mueve objetos y vehículos pesados.',
   uses:'Perfecta para cargar remolques, rovers o estructuras completas de un lado a otro.',
   icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/menu/Icon_Crane.webp',
   tips:'Muy útil en bases industriales donde mover objetos a mano ya no es práctico.'},
  {id:'habitat', name:'Hábitat', en:'Habitat', cat:'estructura', printer:'Inicial (no se imprime)',
   materials:[], desc:'Estructura inicial de aterrizaje: tu primera fuente de energía (RTG integrado) y punto de generación de vehículos.',
   uses:'Punto de partida de toda base; contiene el primer Small Printer y un RTG permanente.',
   icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Shelter.webp',
   tips:'No puede reciclarse ni moverse: planifica tu base alrededor de su ubicación inicial.'}
];
const OBJECT_MAP = Object.fromEntries(OBJECTS.map(o=>[o.id,o]));

/* ---------------- VEHÍCULOS ---------------- */
const VEHICLES = [
  {id:'trailer', name:'Remolque', en:'Trailer', cat:'remolque', printer:'Impresora Pequeña',
   materials:[{id:'aluminum',qty:1}], desc:'Remolque enganchable con ranuras extra de almacenamiento.',
   uses:'Amplía la capacidad de carga de cualquier rover en tus expediciones.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Rover.webp',
   tips:'Combínalo con un Auto Arm en la base para descargar automáticamente al llegar.'},
  {id:'tractor', name:'Tractor', en:'Tractor', cat:'vehiculo', printer:'Impresora Pequeña', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Rover.webp',
   materials:[{id:'aluminum',qty:2}], desc:'Rover pequeño de bajo coste, ágil en terreno irregular.',
   uses:'Ideal para exploración rápida cerca de la base antes de tener vehículos más grandes.',
   tips:'Súbele un Small Generator o Small Wind Turbine si vas a alejarte mucho de tu base.'},
  {id:'medium_rover', name:'Rover Mediano', en:'Medium Rover', cat:'vehiculo', printer:'Impresora Mediana',
   materials:[{id:'ceramic',qty:1},{id:'aluminum',qty:2}], desc:'Rover de tamaño medio con más ranuras y mejor tracción que el Buggy.',
   uses:'Buen equilibrio entre velocidad y capacidad de carga para expediciones medias.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Rover.webp',
   tips:'Puedes engancharle remolques pequeños para transportar más recursos en tus rutas.'},
  {id:'buggy', name:'Buggy', en:'Buggy', cat:'vehiculo', printer:'Impresora Mediana',
   materials:[{id:'aluminum',qty:1},{id:'compound',qty:1}], desc:'Vehículo ligero de un asiento, rápido y con buena maniobrabilidad.',
   uses:'Un salto de calidad respecto al Tractor para desplazarte por la base y alrededores.', icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Rover.webp',
   tips:'Añádele un Rover Seat si vas a llevar a otro astronauta contigo.'},
  {id:'hoverboard', name:'Patineta Voladora', en:'Hoverboard', cat:'vehiculo', printer:'Impresora Mediana',
   materials:[{id:'titanium_alloy',qty:1}], desc:'Vehículo individual que se desliza sobre el terreno sin necesidad de ruedas.',
   uses:'Excelente para moverse rápido sobre terreno muy irregular o cuevas estrechas.',
   icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Hoverboard.webp',
   tips:'Consume energía de tu traje: lleva baterías o un RTG portátil si la vas a usar mucho tiempo.'},
  {id:'large_rover', name:'Rover Grande', en:'Large Rover', cat:'vehiculo', printer:'Impresora Grande',
   materials:[{id:'rubber',qty:2},{id:'aluminum_alloy',qty:2}], desc:'Vehículo de varios asientos con múltiples ranuras Tier 2/3, capaz de llevar remolques largos.',
   uses:'Un cambio radical en logística de mediados de partida: transporta impresoras y estructuras enteras.',
   icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Rover.webp',
   tips:'Puedes montarle una impresora mediana encima para fabricar objetos mientras viajas.'},
  {id:'small_shuttle', name:'Lanzadera Pequeña', en:'Small Shuttle', cat:'vehiculo', printer:'Impresora Grande',
   materials:[{id:'aluminum',qty:2}], desc:'Tu primer vehículo espacial: te lleva a la órbita y a otros planetas.',
   uses:'Imprescindible para dejar Sylva por primera vez y empezar a explorar el sistema.',
   icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Shuttle.webp',
   tips:'Móntale un Solid-Fuel Thruster antes de despegar, y lleva otro de repuesto en la mochila.'},
  {id:'medium_shuttle', name:'Lanzadera Mediana', en:'Medium Shuttle', cat:'vehiculo', printer:'Impresora Grande',
   materials:[{id:'ceramic',qty:2},{id:'aluminum_alloy',qty:1}], desc:'Cohete de mayor capacidad, con más ranuras de carga que la lanzadera pequeña.',
   uses:'Permite llevar vehículos pequeños o varios silos de recursos entre planetas.',
   icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Shuttle.webp',
   tips:'Buen momento para actualizar cuando ya dependas de traer Copper o Tungsten de otro planeta.'},
  {id:'large_shuttle', name:'Lanzadera Grande', en:'Large Shuttle', cat:'vehiculo', printer:'Impresora Grande',
   materials:[{id:'ceramic',qty:2},{id:'titanium_alloy',qty:2}], desc:'El cohete de mayor capacidad, capaz de transportar rovers medianos completos.',
   uses:'Clave para trasladar un Rover Grande o un Tren completo a otro planeta.',
   icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Shuttle.webp',
   tips:'Vuela con Hydrazine Thrusters para maximizar la carga útil en cada viaje.'},
  {id:'vtol', name:'VTOL', en:'VTOL', cat:'vehiculo', printer:'Impresora Grande',
   materials:[{id:'titanium_alloy',qty:2},{id:'hydrazine',qty:2}], desc:'Vehículo de despegue vertical que vuela usando Hidrazina como combustible.',
   uses:'Perfecto para cruzar terrenos imposibles de atravesar en rover, como cañones o montañas.',
   icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_VTOL.webp',
   tips:'Lleva siempre Hidrazina de sobra: sin combustible se queda varado en pleno vuelo.'}
];
const VEHICLE_MAP = Object.fromEntries(VEHICLES.map(v=>[v.id,v]));

/* ---------------- Sistema Ferroviario ---------------- */

const TRAINS = [
  {
    id:'rail_engine', name:'Locomotora', en:'Rail Engine', cat:'tren', printer:'Impresora Mediana',
    materials:[{id:'resin',qty:1}, {id:'aluminum',qty:1}, {id:'copper',qty:1}],
    desc:'Vehículo ferroviario motorizado utilizado para desplazarse por las vías y arrastrar vagones.',
    uses:'Permite transportar al jugador y automatizar rutas entre estaciones ferroviarias.',
    icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Rail_Engine.webp',
    tips:'Puede remolcar varios vagones y dispone de asiento, luz frontal y dos ranuras auxiliares.'
  },

  {
    id:'rail_car', name:'Vagón Ferroviario', en:'Rail Car', cat:'tren', printer:'Impresora Mediana',
    materials:[{id:'resin',qty:2}, {id:'aluminum',qty:1}],
    desc:'Vagón modular que transporta cualquier objeto compatible con su ranura principal.',
    uses:'Ideal para mover recursos, plataformas, silos, contenedores y maquinaria entre bases.',
    icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Rail_Engine.webp',
    tips:'Puedes colocar sobre él un Large Resource Canister, un Large Storage Silo o casi cualquier módulo de tamaño adecuado.'
  },

  {
    id:'rail_station', name:'Estación Ferroviaria', en:'Rail Station', cat:'tren', printer:'Impresora Grande',
    materials:[{id:'titanium',qty:2}, {id:'copper',qty:1}, {id:'quartz',qty:1}],
    desc:'Estación donde los trenes pueden detenerse automáticamente.',
    uses:'Permite cargar, descargar y controlar rutas mediante automatización.',
    icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/menu/Icon_Rail_Station.webp',
    tips:'Combínala con Brazos Automáticos y sensores para crear sistemas logísticos completamente automáticos.'
  },

  {
    id:'rail_post_bundle', name:'Paquete de Postes Ferroviarios', en:'Rail Post Bundle', cat:'tren',
    printer:'Impresora Pequeña',
    materials:[{id:'resin',qty:1}, {id:'aluminum',qty:1}],
    desc:'Contiene 10 postes ferroviarios para construir vías.',
    uses:'Extiende las líneas ferroviarias y también transmite oxígeno y energía.',
    icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Rail_Post.webp',
    tips:'Los postes se conectan automáticamente al colocarlos dentro del alcance.'
  },

  {
    id:'tall_rail_post_bundle', name:'Paquete de Postes Ferroviarios Altos', en:'Tall Rail Post Bundle', cat:'tren',
    printer:'Impresora Pequeña',
    materials:[{id:'resin',qty:1},{id:'aluminum',qty:1}],
    desc:'Versión elevada de los postes ferroviarios.',
    uses:'Ideal para salvar desniveles o construir vías por encima del terreno.',
    icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Rail_Post.webp',
    tips:'Muy útiles para mantener las vías despejadas en terrenos irregulares.'
  },

  {
    id:'rail_junction_bundle', name:'Paquete de Desvíos Ferroviarios', en:'Rail Junction Bundle', cat:'tren', printer:'Impresora Pequeña',
    materials:[{id:'aluminum',qty:2}],
    desc:'Contiene 5 desvíos ferroviarios.',
    uses:'Permite dividir una vía en tres direcciones diferentes.',
    icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Rail_Post.webp',
    tips:'Puedes controlar automáticamente la dirección mediante pines y sensores.'
  }
];
const TRAIN_MAP = Object.fromEntries(TRAINS.map(t=>[t.id,t]));

/* ---------------- AUTOMATIZACIÓN ---------------- */

const AUTOMATION = [
  {
    id:'auto_arm',
    name:'Brazo Automático',
    en:'Auto Arm',
    cat:'automatizacion',
    printer:'Impresora Pequeña',
    materials:[
      {id:'aluminum',qty:1},
      {id:'graphite',qty:1}
    ],
    desc:'Transfiere automáticamente objetos de Nivel 1 entre dos áreas de trabajo.',
    uses:'Clasificación, fabricación automática y transporte de recursos.',
    icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/menu/Icon_Crane.webp',
    tips:'Coloca un recurso en la ranura del filtro para que solo transporte ese objeto.'
  },

  {
    id:'auto_extractor',
    name:'Extractor Automático',
    en:'Auto Extractor',
    cat:'automatizacion',
    printer:'Impresora Grande',
    materials:[
      {id:'steel',qty:2},
      {id:'tungsten_carbide',qty:1},
      {id:'rubber',qty:1},
      {id:'exo_chip',qty:1},
    ],
    desc:'Extrae recursos automáticamente sin destruir el depósito.',
    uses:'Minería continua y granjas automáticas de recursos.',
    icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Auto_Extractor.webp',
    tips:'Produce muchas más unidades por depósito que la Herramienta de Terreno.'
  },

  {
    id:'power_sensor',
    name:'Sensor de Energía',
    en:'Power Sensor',
    cat:'automatizacion',
    printer:'Impresora Pequeña',
    materials:[
      {id:'zinc',qty:1},
      {id:'copper',qty:1}
    ],
    desc:'Envía una señal cuando la energía aparece o desaparece.',
    uses:'Encender generadores, luces o módulos automáticamente.',
    icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Sensor.webp',
    tips:'Muy útil para crear sistemas de energía de respaldo.'
  },

  {
    id:'storage_sensor',
    name:'Sensor de Almacenamiento',
    en:'Storage Sensor',
    cat:'automatizacion',
    printer:'Impresora Pequeña',
    materials:[
      {id:'zinc',qty:1},
      {id:'quartz',qty:1}
    ],
    desc:'Detecta cuándo un almacenamiento está lleno o vacío.',
    uses:'Automatizar impresoras, brazos y trenes.',
    icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Sensor.webp',
    tips:'Perfecto para lanzar automáticamente plataformas de intercambio o controlar estaciones ferroviarias.'
  },

  {
    id:'battery_sensor',
    name:'Sensor de Batería',
    en:'Battery Sensor',
    cat:'automatizacion',
    printer:'Impresora Pequeña',
    materials:[
      {id:'zinc',qty:1},
      {id:'graphite',qty:1}
    ],
    desc:'Detecta el estado de carga de las baterías conectadas.',
    uses:'Control inteligente del consumo eléctrico.',
    icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Sensor.webp',
    tips:'Puede activar generadores únicamente cuando la batería esté descargándose.'
  },

  {
    id:'button_repeater',
    name:'Repetidor de Botón',
    en:'Button Repeater',
    cat:'automatizacion',
    printer:'Impresora Pequeña',
    materials:[
      {id:'zinc',qty:1}
    ],
    desc:'Envía una señal cada vez que se activa.',
    uses:'Disparador manual para cualquier circuito lógico.',
    icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Sensor.webp',
    tips:'Es el repetidor más sencillo para iniciar automatizaciones.'
  },

  {
    id:'delay_repeater',
    name:'Repetidor con Retardo',
    en:'Delay Repeater',
    cat:'automatizacion',
    printer:'Impresora Pequeña',
    materials:[
      {id:'zinc',qty:1}
    ],
    desc:'Retrasa el envío de una señal durante un tiempo configurable.',
    uses:'Temporizadores y secuencias automáticas.',
    icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Sensor.webp',
    tips:'Ideal para sincronizar varios módulos.'
  },

  {
    id:'count_repeater',
    name:'Repetidor Contador',
    en:'Count Repeater',
    cat:'automatizacion',
    printer:'Impresora Pequeña',
    materials:[
      {id:'zinc',qty:1}
    ],
    desc:'Activa una señal después de recibir un número determinado de impulsos.',
    icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Sensor.webp',
    uses:'Contadores, ciclos automáticos y control de procesos.',
    tips:'Muy útil junto con los sensores de almacenamiento.'
  },

  {
    id:'proximity_repeater',
    name:'Repetidor de Proximidad',
    en:'Proximity Repeater',
    cat:'automatizacion',
    printer:'Impresora Pequeña',
    materials:[
      {id:'zinc',qty:1}
    ],
    desc:'Activa objetos automáticamente cuando un jugador o vehículo entra en su alcance.',
    uses:'Puertas automáticas, luces y sistemas interactivos.',
    icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Sensor.webp',
    tips:'También puede activar plantas y muestras de investigación.'
  },

  {
    id:'power_switch',
    name:'Switch de Energía',
    en:'Power Switch',
    cat:'automatizacion',
    printer:'Impresora Pequeña',
    materials:[
      {id:'copper',qty:1}
    ],
    desc:'Permite abrir o cerrar manualmente una línea eléctrica.',
    icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Splitter.webp',
    uses:'Aislar máquinas o activar circuitos específicos.',
    tips:'Muy útil para apagar módulos con alto consumo.'
  },

  {
    id:'extenders',
    name:'Extensores',
    en:'Extenders',
    cat:'automatizacion',
    printer:'Impresora Pequeña',
    materials:[
      {id:'copper',qty:1}
    ],
    desc:'Amplían el alcance de las conexiones de energía y oxígeno.',
    uses:'Llevar energía a minas, estaciones ferroviarias y bases remotas.',
    icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Extenders.webp',
    tips:'No consumen energía y son esenciales para bases grandes.'
  },

  {
    id:'splitter',
    name:'Divisor de Energía',
    en:'Splitter',
    cat:'automatizacion',
    printer:'Impresora Pequeña',
    materials:[
      {id:'copper',qty:1},
      {id:'graphite',qty:1}
    ],
    desc:'Distribuye la energía entre varias salidas.',
    uses:'Priorizar el suministro eléctrico de determinados módulos. Permite conectar más módulos de energía o de automatización sin ranuras libres.',
    icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Splitter.webp',
    tips:'Muy útil en bases compactas donde te falten puertos de conexión.'
  },

  {
    id:'tapper',
    name:'Extractor de Savia',
    en:'Tapper',
    cat:'automatizacion',
    printer:'Impresora Pequeña',
    materials:[
      {id:'aluminum',qty:1}
    ],
    desc:'Recolecta automáticamente recursos orgánicos de plantas compatibles.',
    uses:'Producción continua de recursos vegetales.',
    icon:'https://danirp23.github.io/Astroneer_Guia_Offline/assets/objects/Icon_Tapper.png',
    tips:'Introducido en una actualización posterior como complemento de la automatización.'
  }
];
const AUTOMATION_MAP = Object.fromEntries(AUTOMATION.map(a=>[a.id,a]));

/* Todos los "items fabricables" (objetos+vehículos+trenes+automatización) en un solo mapa,
   útil para calcular en qué construcciones participa cada recurso. */
const ALL_ITEMS = [...OBJECTS, ...VEHICLES, ...TRAINS, ...AUTOMATION];
